config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'static_pages/home'

  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  resources :users
  get    '/login',   to: 'sessions#new'
  
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'comments/create'

  get 'comments/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  
  resources :favorites, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  
  resources :posts
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  content    :text
#  name       :string
#  picture    :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#

class Post < ApplicationRecord
    #Commentモデルを複数持てる様にする
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :delete_all
    has_many :post_tag_relations, dependent: :delete_all # 追加
    has_many :tags, through: :post_tag_relations  #追加
    belongs_to:user
    default_scope -> { order(created_at: :desc) }
    # presence -> 必須チェック
    # length -> 文字数の制限
   # validates :name, presence: true, length: { maximum: 30 }
    validates :title, presence: true, length: { maximum: 30 }
    validates :content, presence: true, length: { maximum: 1000 }
    validates :user_id,presence:true
    #画像のアップロード機能を持たせる
    mount_uploader :picture, PictureUploader
    validates :user, presence:true
    
    #favoriteモデル追加
    has_many :favorites, dependent: :destroy
    has_many :users, through: :favorites
    validates :user_id,presence: true
    validates :content, presence: true, length: { maximum: 140 }
    
end

app/controllers/concerns/posts_controller.rb
# Applicationcontrollerクラスを継承することで、クラスがコントローラと認識される
class PostsController < ApplicationController
    def index
        # 追加
        # タグが選択されている場合は、タグに関連されているデータを取得、そうでなければ全てのデータを取得(ただし、データの全検索はしてない)
        @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    
        # page メソッドを呼ぶと引数に指定したページに表示するデータ分だけ取得(デフォルトは、25件)
        @posts = Post.page(params[:page])
    end
    
    #ルーティングの変更後に追加
    def new
        @post = Post.new(flash[:board])
    end
    
     def create
         # Post モデルを引数のパラメータで初期化(データの保存は指定ない)
        post = Post.create(post_params)
        
        
         # フラッシュ
        # 保存の正否をチェック
   if post.save
      # フラッシュ
      flash[:notice] = "「#{post.title}」の記事が投稿されました!"
      redirect_to post
    else
    redirect_to new_post_path, flash: {
      post: post,
      error_messages: post.errors.full_messages
    }
   end
   #ユーザーと投稿を紐付けするときに追加
    
   
   
     end

    
    # findメソッドで、idにひもづくPOSTオブジェクトを取得する
    def show
     @post = Post.find_by(id: params[:id])
     # @comment = @post.comments.new
    
    @comment = Comment.new(post_id: @post.id)
    end
    
    # 追加
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        post = Post.find(params[:id])
        # モデルの更新は、クラスメソッドのupdateメソッドで行える
        post.update(post_params)
        
        # フラッシュ
        flash[:notice] = "「#{@post.title}」の記事を更新しました!"
        
        # リダイレクト処理
        redirect_to @post
    end
    
    # 削除機能
    def destroy
        comment = Comment.find(params[:id])
        @post.destroy
        
         # フラッシュ 
        flash[:notice] = "「#{@post.title}」の記事を削除しました!"
        
        # 投稿一覧へリダイレクト
        redirect_to posts_path
    end
    
    private
    
    #paramsから欲しいデータのみ抽出
    def post_params
        #params.require(:post).permit(:name, :title, :content)
        # tag_ids をリストで追加
        params.require(:post).permit(:name, :title, :content, tag_ids: [])
    end
    
    def set_target_post
        @post = Post.find(params[:id])
    end
    
end

app/controllers/posts_controller.rb
# Applicationcontrollerクラスを継承することで、クラスがコントローラと認識される
class PostsController < ApplicationController
    def index
        # 追加
        # タグが選択されている場合は、タグに関連されているデータを取得、そうでなければ全てのデータを取得(ただし、データの全検索はしてない)
        @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    
        # page メソッドを呼ぶと引数に指定したページに表示するデータ分だけ取得(デフォルトは、25件)
        @posts = Post.page(params[:page])
        
    end
    
    #ルーティングの変更後に追加
    def new
        @post = Post.new(flash[:board])
    end
    
     def create
         # Post モデルを引数のパラメータで初期化(データの保存は指定ない)
        post = Post.create(post_params)
        
        
         # フラッシュ
        # 保存の正否をチェック
   if post.save
      # フラッシュ
      flash[:notice] = "「#{post.title}」の記事が投稿されました!"
      redirect_to post
    else
    redirect_to new_post_path, flash: {
      post: post,
      error_messages: post.errors.full_messages
    }
   end
     end

    
    # findメソッドで、idにひもづくPOSTオブジェクトを取得する
    def show
     @post = Post.find(params[:id])
     # @comment = @post.comments.new
    @comment = Comment.new(post_id: @post.id)
    end
    
    # 追加
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        post = Post.find(params[:id])
        # モデルの更新は、クラスメソッドのupdateメソッドで行える
        post.update(post_params)
        
        # フラッシュ
        flash[:notice] = "「#{@post.title}」の記事を更新しました!"
        
        # リダイレクト処理
        redirect_to @post
    end
    
    # 削除機能
    def destroy
        
        @post = Post.destroy(params[:id])
        
         # フラッシュ 
        flash[:notice] = "「#{@post.title}」の記事を削除しました!"
        
        # 投稿一覧へリダイレクト
        redirect_to posts_path
    end
    
    private
    
    #paramsから欲しいデータのみ抽出
    def post_params
        #params.require(:post).permit(:name, :title, :content)
        # tag_ids をリストで追加 #tagがうまくいかない
        params.require(:post).permit(:user_id,:name, :title, :content, :picture, :tag_ids)
        
        
    end
    
    def set_target_post
        @post = Post.find(params[:id])
    end
    
end

app/views/posts/_comment_form.html.erb
<div class="p-comment__formBox">
  <p class="p-comment__formTitle">コメント記入</p>
  <%= form_for comment do |f| %>
    <%= f.hidden_field :post_id %>
    <div class="form-group">
      <%= f.label :name, '名前' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :comment, 'コメント' %>
      <%= f.text_area :comment, class: 'form-control', rows: 4 %>
    </div>
    <%= f.submit '送信', class: 'btn btn-info btn-block' %>
  <% end %>
</div>

app/views/posts/_form.html.erb
<!-- 追加 -->
<% if flash[:error_messages] %>
    <div class="alert alert-danger">
        <ul>
            <% flash[:error_messages].each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<!-- 追加 -->
<%= render 'shared/error_messages' %>


<%= form_for post do |f| %>
    

    
    <div class="form-group">
        <p>投稿者:<%= #不明なコード%></p>
    </div>
    
    
    
    
    
    <div class="form-group">
        <%= f.label :title, '投稿タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
        <small id="title-tip" class="form-text text-muted">
            タイトルを入力してください。
        </small>
    </div>
    <div class="form-group">
        <%= f.label :content, '投稿内容' %>
        <%= f.text_area :content, class: 'form-control', rows:10 %>
        <small id="content-tip" class="form-text text-muted">
            投稿内容を入力してください。 
        </small>
    </div>
    
    <div class="form-group">
        <%= f.label :content, '参考にしたレシピ' %>
        <%= f.text_area :content, class: 'form-control' %>
        <small id="content-tip" class="form-text text-muted">
            参考にしたレシピのサイトURLを入力してください。 
        </small>
    </div>
    
    <div class="form-group">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>
    
    
    <div class="field">
    <%= f.label :つくったごはんの写真 %>
    <%= f.file_field :picture, id: :post_picture %>
      </div>
    <br></br>
    <%= f.submit '投稿', class: 'btn btn-info btn-block' %>
    <small id="submit-tip" class="form-text text-muted">
        投稿する前に投稿内容を見直してください!
    </small>
    <%= f.hidden_field :user_id, value: current_user.id %>
<% end %>

app/views/posts/_post.html.erb
<div class="card">
  <div class="card-header bg-info text-white">
      <h4><%= post.title %></h4>
      <!-- 追加 -->
      <% post.tags.each do |tag| %>
        <span class="badge badge-light"><%= tag.name %></span>
      <% end %>
  </div>
  <div class="card-body">
      <p class="card-text"><%= simple_format(post.content) %></p>
  </div>
  <div class="card-footer">
      <p class="text-right font-weight-bold mr-10"><%= post.name %></p>
  </div>
</div>


<li id="post-<%= post.id %>">
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/posts/edit.html.erb
<div class="d-flex align-items-center">
  <h1>編集</h1>
  <div class="ml-auto posts_button">
      <%= link_to '投稿一覧', posts_path, class: 'btn btn-outline-info' %>
  </div>
</div>
<%= form_for @post do |f| %>
    <div class="form-group">
        <%= f.label :name, '投稿者名' %>
        <%= f.text_field :name, class: 'form-control' %>
        <small id="poster-tip" class="form-text text-muted">
            あなたの名前を入力してください。
        </small>
    </div>
    <div class="form-group">
        <%= f.label :title, '投稿タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
        <small id="title-tip" class="form-text text-muted">
            タイトルを入力してください。
        </small>
    </div>
    <div class="form-group">
        <%= f.label :content, '投稿内容' %>
        <%= f.text_area :content, class: 'form-control', rows:10 %>
        <small id=content-tip" class="form-text text-muted">
            投稿内容を入力してください。 
        </small>
    </div>
    <%= f.submit '投稿', class: 'btn btn-info btn-block' %>
    <small id="submit-tip" class="form-text text-muted">
        投稿する前に投稿内容を見直してください!
    </small>
<% end %>

app/views/posts/index.html.erb
<div class="d-flex align-items-center">
    <h1>投稿一覧</h1>
    <div class="ml-auto posts_button">
        <%= form_tag posts_path, method: :get, class: 'posts__searchForm' do %>
            <%= select_tag :tag_id,
                           options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                           {
                             prompt: 'タグで絞り込み',
                             class: 'form-control posts__select',
                             onchange: 'submit(this.form);'
                             }
             %>
     <% end %>
        <%= link_to '投稿', new_post_path, class: "btn btn-outline-info" %> 
    </div>
</div>

<% if flash[:notice] %>
    <div class="alert alert-primary"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered border-primary table-hover table-sm posts_table">
  <thead class="bg-info text-light">
    <tr>
      <th scope="col">No.</th>
      <th scope="col">投稿タイトル</th>
      <th scope="col">投稿画像</th>
      <th scope="col">投稿者</th>
      <th scope="col">投稿日</th>
      <th scope="col">更新日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      <% @posts.each do |post| %>
        <tr>
            <th><%= post.id %></th>
            <td><%= post.title %></td>
            <td><%= image_tag post.picture.to_s %></td>
            <td><%= post.name %></td>
            <td><%= post.created_at.to_s(:datetime_base) %></td>
            <td><%= post.updated_at.to_s(:datetime_base) %></td>
            <td><%= link_to "詳細" , post, class: 'btn btn-outline-info' %></td>
            <td><%= link_to "削除" , post, class: 'btn btn-outline-info', method: :delete, data: {confirm: "投稿記事を削除しますか？", cancel: "キャンセル", commit: "削除する", title: "削除の確認"} %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<div class="d-flex align-items-center">
  <h1>投稿</h1>
  <div class="ml-auto posts_button">
      <!-- 修正 -->
      <%= link_to '投稿一覧', posts_path, class: 'btn btn-outline-info' %>
  </div>
</div>

<!--パーシャルファイルを呼び出す -->
<%= render partial: 'form', locals: { post: @post} %>

app/views/posts/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
    <div class="ml-auto posts_button">
        <!-- 修正 -->
  　    <%= link_to '投稿一覧', posts_path, class: "btn btn-outline-info" %>
      <%= link_to '編集', edit_post_path(@post), class: "btn btn-outline-info" %>
    </div>
</div>

<!-- 追加 -->
<% if flash[:notice] %>
    <div class="alert alert-primary"><%= flash[:notice] %></div>
<% end %>

<%= render @post %>

<!-- 追加 -->
<div class="p-comment_list">
  <div class="p-comment_listTitle">コメント</div>
  <%= render @post.comments %>
</div>

<!-- 画像アップロード機能-->
<p>
  <strong>Picture:</strong>
  <%= image_tag(@post.picture_url) if @post.picture.present? %>
</p>


<!-- 0907コメント機能追加の際修正-->
<%= render partial: 'comments/form', locals: { comment: @comment } %>