config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'static_pages/home'

  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  resources :users
  get    '/login',   to: 'sessions#new'
  
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'comments/create'

  get 'comments/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  
  resources :favorites, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  
  resources :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  

  
end

app/helpers/application_helper.rb
module ApplicationHelper
    # 表示名とパスを受け取る
    def header_link_item(name, path)
        # bootstrapのnavbar-navの子クラスにしたいので、nav-itemをクラス名に指定
        class_name = 'nav-item'
        # ヘルパーメソッドの呼び出し。アクティブなページの場合、クラスにactiveの文言を追加してヘッダーの対象文字を活性化する
        class_name << ' active' if current_page?(path)

        # 任意のhtmlタグを作成するためのヘルパーメソッド
        content_tag :li, class: class_name do
            link_to name, path, class: 'nav-link'
        end
    end
end

app/views/application/_footer.html.erb
<!-- Footer -->
<footer class="container-fluid bg-4 text-center">
  
  <p>サイト改善等ご要望は<%= link_to "こちら", root_path, class: "btn" %></p>
</footer>

</body>
</html>

app/views/application/_header.html.erb
<%= stylesheet_link_tag "base" %>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <%= link_to image_tag('logo.png',{:size => '180x50', :border =>'0', :alt => 'ホーム'}), root_path %>
    </div>
    
    
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <ul><%= link_to"投稿", posts_path %></ul>
          <ul class="nav nav-pills">
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィ－ル", current_user %></li>
              <li><%= link_to "設定", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </ul>
          
            
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
          <%= link_to "新規登録", signup_path %>
        <% end %>
    
        
        
      </ul>
    </div>
  </div>
</nav>

<!--<div class="topnav">
    <%= header_link_item('ホーム', root_path) %>
        <%= header_link_item('投稿一覧', posts_path) %>
       <%= link_to "Tsukutta!とは",   about_path %>
      
        <% if logged_in? %>
          <li><%= link_to "ユーザー一覧", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", current_user %></li>
              <li><%= link_to "設定", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
    
  </div>
  --!>